-- CubeSat COTS component catalog
-- Generated from the researched catalog on 31 Aug 2026
-- SQLite-compatible SQL

DROP TABLE IF EXISTS cubesat_cots;
CREATE TABLE cubesat_cots (
    id INTEGER PRIMARY KEY,
    tree_location TEXT NOT NULL,
    item_type TEXT NOT NULL,
    product_name TEXT NOT NULL,
    product_url TEXT,
    vendor TEXT,
    description TEXT,
    published_price TEXT,
    availability TEXT,
    procurement_class TEXT
);

INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (1, 'Electrical / Avionics → Communications • Antenna', 'Amplified S-band antenna', 'EXA SSA02 34 dB Amplified S-band Patch Antenna', 'https://www.cubesatshop.com/product-category/antenna-systems/', 'EXA', 'Amplified S-band patch antenna with integrated gain stage.', '€9,400', 'Active CubeSatShop listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (2, 'Electrical / Avionics → Communications • Antenna', 'GNSS antenna', 'EXA GCA01 Compact GNSS Active Patch Antenna', 'https://www.cubesatshop.com/product-category/antenna-systems/', 'EXA', 'Compact active GNSS patch antenna listed for nanosatellite use.', '€1,700', 'Active CubeSatShop listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (3, 'Electrical / Avionics → Communications • Antenna', 'GNSS antenna', 'EnduroSat GNSS Patch Antenna L1+L2+L5', 'https://www.endurosat.com/products/gnss-patch-antenna-l1-l2/', 'EnduroSat', 'Multi-band GNSS patch antenna supporting L1, L2 and L5.', '$8,200', 'Active product; order/inquiry via vendor', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (4, 'Electrical / Avionics → Communications • Antenna', 'GNSS antenna', 'EnduroSat GNSS Patch Antenna L1/E1', 'https://www.endurosat.com/products/gnss-patch-antenna/', 'EnduroSat', 'Compact active GNSS patch antenna for L1/E1 navigation reception.', '$5,500', 'Active product; order/inquiry via vendor', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (5, 'Electrical / Avionics → Communications • Antenna', 'S-band TM/TC antenna', 'ISISPACE S-band TMTC Antenna', 'https://www.isispace.nl/product/s-band-tmtc-antenna/', 'ISISPACE', 'S-band telemetry/telecommand antenna for nanosatellite missions.', 'Quote required', 'Current vendor product; contact sales', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (6, 'Electrical / Avionics → Communications • Antenna', 'S-band antenna', 'EXA SSA01 Wide-Bandwidth S-band Patch Antenna', 'https://www.cubesatshop.com/product-category/antenna-systems/', 'EXA', 'Compact wide-bandwidth S-band patch antenna.', '€2,200', 'Active CubeSatShop listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (7, 'Electrical / Avionics → Communications • Antenna', 'S-band antenna', 'EnduroSat S-Band Antenna Wideband', 'https://www.endurosat.com/products/', 'EnduroSat', 'Wideband S-band patch antenna for CubeSat/smallsat links.', '$6,700', 'Active product listing', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (8, 'Electrical / Avionics → Communications • Antenna', 'UHF antenna', 'EnduroSat UHF Antenna 2U', 'https://www.endurosat.com/products/uhf-antenna-2u/', 'EnduroSat', 'Deployable VHF/UHF antenna covering 144–438 MHz with triple-redundant burn-wire deployment.', '$10,400–$15,600', 'Active product; order/inquiry via vendor', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (9, 'Electrical / Avionics → Communications • Radio', 'S-band radio/transceiver', 'EnduroSat S-Band Transceiver', 'https://www.endurosat.com/products/s-band-transceiver/', 'EnduroSat', 'Full-duplex S-band transceiver, 5–125 kbps, 11–28 V input, ~246 g.', '$17,500', 'Active product; order/inquiry via vendor', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (10, 'Electrical / Avionics → Communications • Radio', 'S-band transmitter', 'IQ Spacecom S-Band Transmitter', 'https://www.cubesatshop.com/product-category/communication-systems/', 'IQ Spacecom', 'S-band transmitter listed in CubeSatShop communication systems.', '€6,500', 'Active CubeSatShop listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (11, 'Electrical / Avionics → Communications • Radio', 'Simplex satellite radio', 'EyeStar-S3 Satellite Simplex Communications System', 'https://www.cubesatshop.com/product-category/communication-systems/', 'NearSpace Launch', 'Simplex satellite communication system sold through CubeSatShop.', '€2,100–€6,600', 'Active CubeSatShop listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (12, 'Electrical / Avionics → Communications • Radio', 'UHF radio/transceiver', 'EnduroSat UHF Transceiver II', 'https://www.endurosat.com/products/uhf-transceiver-ii/', 'EnduroSat', 'CubeSat UHF transceiver for 400–403 or 435–438 MHz; up to 19.6 kbps; ~8 W typical transmit consumption.', '$7,900', 'Active product; order/inquiry via vendor', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (13, 'Electrical / Avionics → Communications • Radio', 'X-band SDR', 'EnduroSat X-Band Software Defined Radio', 'https://www.endurosat.com/products/x-band-sdr/', 'EnduroSat', 'High-rate X-band software-defined radio for payload/mission downlink.', '$180,000', 'Active product; order/inquiry via vendor', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (14, 'Electrical / Avionics → Computational • OBC', 'Flight computer', 'CyBER OBC', 'https://quantumgalactics.com/products/CyBER_OBC/', 'Quantum Galactics', 'Configurable on-board computer offered as engineering/flight model configurations.', 'From €16,310 excl. tax/customs', 'Current vendor listing; configurable', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (15, 'Electrical / Avionics → Computational • OBC', 'Flight computer', 'EnduroSat Onboard Computer', 'https://www.endurosat.com/products/onboard-computer/', 'EnduroSat', 'ARM Cortex-M7 OBC with ECC storage, redundant FRAM/NAND and CAN/CAN-FD/RS422/485/SPI/I²C/UART/Ethernet interfaces.', '$16,000–$26,000', 'Active product; order/inquiry via vendor', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (16, 'Electrical / Avionics → Computational • OBC', 'Flight computer', 'ISISPACE On Board Computer (iOBC)', 'https://www.cubesatshop.com/product/isis-on-board-computer/', 'ISISPACE', 'CubeSat on-board computer with flight heritage; available in multiple variants.', 'Quote required', 'CubeSatShop currently shows out of stock / request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (17, 'Electrical / Avionics → Computational • OBC', 'Flight computer', 'NanoMind A3200', 'https://gomspace.com/product/nanomind-a3200/', 'GomSpace', 'Established GomSpace nanosatellite flight computer family; CAN/I²C and integrated sensor options.', 'Quote required', 'Current vendor product; contact sales', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (18, 'Electrical / Avionics → Computational • OBC', 'Integrated OBC/ADCS/radio', 'NanoAvionics SatBus 3C2', 'https://nanoavionics.com/cubesat-components/satbus-3c2/', 'NanoAvionics', 'Integrated CubeSat avionics unit combining OBC, ADCS functions and redundant UHF communications.', 'From €4,460 (minimum order 3)', 'Current vendor listing; lead time by inquiry', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (19, 'Electrical / Avionics → Computational • OBC', 'OBC + spacecraft core', 'EXA ICEPS Spacecraft System Core', 'https://www.cubesatshop.com/product/iceps-spacecraft-system-core/', 'EXA', 'Integrated command/data handling and spacecraft core with multiple configurations.', '€20,500–€66,000', 'Active CubeSatShop listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (20, 'Electrical / Avionics → Interconnect', 'Board connector', 'Harwin M80-5102022 20-position Header', 'https://www.digikey.no/en/products/detail/harwin-inc/M80-5102022/2271988', 'Harwin / DigiKey', '20-position threaded Datamate board connector, -55 °C to +125 °C.', 'NOK 156.44 ea.', '500+ reported in stock', 'High-reliability engineering COTS — qualify for mission');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (21, 'Electrical / Avionics → Interconnect', 'Connector contact', 'Harwin M80-0190005 Contact', 'https://www.digikey.no/en/products/detail/harwin-inc/M80-0190005/3307287', 'Harwin / DigiKey', 'Datamate rectangular-connector contact for harness construction.', 'NOK 14.56 ea.', '55,000+ reported in stock', 'High-reliability engineering COTS — qualify for mission');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (22, 'Electrical / Avionics → Interconnect', 'High-reliability connector', 'Harwin Datamate M80-5112042', 'https://www.digikey.no/en/products/detail/harwin-inc/M80-5112042/3724376', 'Harwin / DigiKey', 'Threaded high-reliability 2 mm-pitch Datamate connector; a useful spacecraft-interconnect candidate.', 'NOK 172.84 ea.', '500 reported in stock', 'High-reliability engineering COTS — qualify for mission');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (23, 'Electrical / Avionics → Power • Battery', 'Battery', 'EXA BA0x High Energy Density Battery Array', 'https://www.cubesatshop.com/product/ba0x-high-energy-density-battery-array/', 'EXA', 'Modular nanosatellite battery family, roughly 22.2–50 Wh per bank depending configuration.', '€4,400–€9,425', 'Published availability: 4–6 weeks', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (24, 'Electrical / Avionics → Power • Battery', 'Battery', 'EXA TITAN-1 High Energy Density Battery Matrix', 'https://www.cubesatshop.com/product/titan-1-high-energy-density-battery-matrix/', 'EXA', 'Large ~350 Wh modular battery matrix for higher-power spacecraft.', '€50,000–€62,500', 'Published availability: 6–8 weeks', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (25, 'Electrical / Avionics → Power • EPS', 'EPS', 'Crystalspace P1U “Vasik”', 'https://www.cubesatshop.com/products/', 'CrystalSpace', 'Compact CubeSat power-system module.', '€4,400', 'Active CubeSatShop listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (26, 'Electrical / Avionics → Power • EPS', 'EPS', 'ISISPACE Compact Electrical Power System', 'https://www.isispace.nl/product/compact-electrical-power-system/', 'ISISPACE', 'Compact EPS in 2-cell and 4-cell battery configurations, with flight heritage.', 'Quote required', 'Current vendor product; contact sales', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (27, 'Electrical / Avionics → Power • EPS', 'EPS', 'ISISPACE Modular Electrical Power System', 'https://www.cubesatshop.com/product/isis-modular-electrical-power-system/', 'ISISPACE', 'Modular CubeSat electrical power system sold through CubeSatShop.', 'Quote required', 'Active listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (28, 'Electrical / Avionics → Power • EPS', 'EPS + battery', 'EnduroSat CubeSat EPS', 'https://www.endurosat.com/products/cubesat-eps/', 'EnduroSat', 'CubeSat electrical power system with integrated 99 Wh battery pack and regulated 3.3/5/12/28 V rails.', '$62,000–$75,000', 'Active product; order/inquiry via vendor', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (29, 'Electrical / Avionics → Power • Solar', 'Deployable solar array', 'EXA DMSA Deployable Multifunction Solar Array', 'https://www.cubesatshop.com/product/solar-panels/', 'EXA', 'Deployable array with optional embedded antenna, magnetorquer and sensors.', '€4,400–€20,000', 'Active listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (30, 'Electrical / Avionics → Power • Solar', 'Deployable solar array', 'EnduroSat 3U Deployable Solar Array', 'https://www.endurosat.com/products-category/power-modules/', 'EnduroSat', 'Deployable 3U CubeSat solar-array configurations.', '$26,800–$40,000', 'Active catalog listing', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (31, 'Electrical / Avionics → Power • Solar', 'Deployable solar array', 'EnduroSat 6U Deployable Solar Array', 'https://www.endurosat.com/products-category/power-modules/', 'EnduroSat', 'Deployable 6U CubeSat solar-array configurations.', '$59,000–$88,000', 'Active catalog listing', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (32, 'Electrical / Avionics → Power • Solar', 'Solar panel', 'DHV-CS-10 CubeSat Solar Panel', 'https://www.cubesatshop.com/product-category/nanosatellite-solar-panels/', 'DHV Technology', 'Flight-heritage CubeSat solar panel listed by CubeSatShop.', '€1,450', 'Active CubeSatShop listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (33, 'Electrical / Avionics → Power • Solar', 'Solar panel', 'EnduroSat 3U Solar Panel', 'https://www.endurosat.com/products-category/power-modules/', 'EnduroSat', 'Rigid 3U CubeSat solar-panel product family.', '$7,900', 'Active catalog listing', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (34, 'Electrical / Avionics → Power • Solar', 'Solar panel', 'EnduroSat 6U Solar Panel', 'https://www.endurosat.com/products-category/power-modules/', 'EnduroSat', 'Rigid 6U CubeSat solar-panel product family.', '$20,000', 'Active catalog listing', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (35, 'Electrical / Avionics → Power • Solar', 'Solar panel', 'ISISPACE Small Satellite Solar Panels', 'https://www.isispace.nl/product/small-satellite-solar-panels/', 'ISISPACE', 'GaAs solar panels in 1U–8U/16U and custom sizes; deployable configurations also offered.', 'Quote required', 'Current product; contact sales', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (36, 'Electrical / Avionics → Sensors • IMU', 'Gyro + accelerometer IMU', 'ADIS16495-3BMLZ', 'https://www.digikey.com/en/products/filter/motion-sensors/imus-inertial-measurement-units/567', 'Analog Devices / DigiKey', '6-DOF tactical-grade IMU combining accelerometers and gyros; SPI interface.', '$5,011.64', '6 reported in stock', 'Engineering COTS — not space-qualified by default');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (37, 'Electrical / Avionics → Sensors • IMU', 'Gyro + accelerometer IMU', 'ADIS16505-2BMLZ', 'https://www.digikey.com/en/products/detail/analog-devices-inc/ADIS16505-2BMLZ/11483484', 'Analog Devices / DigiKey', '6-axis precision IMU, ±8 g class, 500 dps range; SPI.', '$1,046.59', '50 reported in stock; manufacturer lead ~26 weeks', 'Engineering COTS — not space-qualified by default');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (38, 'Electrical / Avionics → Sensors • Pressure', 'Pressure sensor', 'Honeywell TruStability HSCDANN005PGAA3', 'https://www.digikey.com/en/products/detail/honeywell-sensing-and-productivity-solutions/HSCDANN005PGAA3/27510987', 'Honeywell / DigiKey', 'Board-mount pressure sensor candidate for lab/contained payload plumbing.', '~$47.09 at qty 100', 'Available to order; ~16-week lead; not stocked in cited listing', 'Engineering COTS — qualification required');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (39, 'Electrical / Avionics → Sensors • Temperature/Humidity', 'Temperature/humidity sensor', 'Sensirion SHT45-AD1B-R3', 'https://www.digikey.no/en/products/detail/sensirion-ag/SHT45-AD1B-R3/21281573', 'Sensirion / DigiKey', 'Digital temperature and humidity sensor; useful for engineering models or environmental monitoring, but not inherently space-qualified.', 'NOK 55.56 ea.', '6,000+ reported in stock; ~10-week standard lead', 'Engineering COTS — qualification required');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (40, 'ADCS → Actuators • CMG', 'Control moment gyro', 'Tensor Tech CMG-10m', 'https://www.cubesatshop.com/product/reaction-sphere/', 'Tensor Tech', 'Compact control-moment-gyro actuator for agile small spacecraft.', '$22,000', 'Active listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (41, 'ADCS → Actuators • CMG', 'Control moment gyro', 'Tensor Tech CMG-20m', 'https://www.cubesatshop.com/product/tensor-tech-cmg-20m-control-moment-gyroscope/', 'Tensor Tech', 'Mid-capacity control-moment gyro for smallsat attitude control.', 'Quote required', 'Active listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (42, 'ADCS → Actuators • Magnetorquer', 'Magnetorquer', 'EXA MT01 Compact Magnetorquer', 'https://www.cubesatshop.com/product/mt01-compact-magnetorquer/', 'EXA', 'Thin, lightweight magnetorquer for roughly 1U–3U class missions.', '€1,000–€1,200', 'Published availability: 2 weeks', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (43, 'ADCS → Actuators • Magnetorquer', 'Magnetorquer rod', 'NCTR-M002 Magnetorquer Rod', 'https://www.cubesatshop.com/product-category/attitude-actuators/', 'NewSpace Systems', 'Magnetic attitude-control rod listed by CubeSatShop.', '$1,200', 'Active listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (44, 'ADCS → Actuators • Magnetorquer', 'Magnetorquer rod', 'NCTR-M012 Magnetorquer Rod', 'https://www.cubesatshop.com/product-category/attitude-actuators/', 'NewSpace Systems', 'Higher-moment magnetic attitude-control rod.', '$2,000', 'Active listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (45, 'ADCS → Actuators • Reaction wheel', 'Reaction wheel', 'MAI-400 Reaction Wheel', 'https://www.cubesatshop.com/product-category/attitude-actuators/', 'Maryland Aerospace', 'CubeSat reaction wheel listed in CubeSatShop attitude actuators.', '$7,100', 'Active listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (46, 'ADCS → Actuators • Reaction wheel', 'Reaction wheel family', 'CubeSpace Reaction Wheels', 'https://www.cubespace.co.za/products/reaction-wheels/', 'CubeSpace', 'Reaction-wheel family spanning multiple momentum capacities.', 'Quote required', 'Published lead time: 12 weeks', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (47, 'ADCS → Attitude sensors • Earth', 'Earth sensor', 'MAI-SES IR Earth Sensor', 'https://www.cubesatshop.com/product-category/attitude-sensors/', 'Maryland Aerospace / CubeSatShop', 'Infrared Earth sensor for attitude determination.', '$14,900', 'Active CubeSatShop category listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (48, 'ADCS → Attitude sensors • Magnetometer', 'Magnetometer', 'CubeSpace Magnetometer', 'https://www.cubespace.co.za/products/magnetometers/', 'CubeSpace', 'Nanosatellite magnetometer for attitude determination.', 'Quote required', 'Published lead time: 8 weeks', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (49, 'ADCS → Attitude sensors • Magnetometer', 'Magnetometer', 'NewSpace Systems Magnetometer', 'https://www.cubesatshop.com/product/nss-magnetometer/', 'NewSpace Systems', 'Standalone spacecraft magnetometer sold through CubeSatShop.', '$15,000', 'Active listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (50, 'ADCS → Attitude sensors • Star', 'Star tracker', 'NST-3 Nano Star Tracker', 'https://www.cubesatshop.com/product/nst-3-nano-star-tracker/', 'NewSpace Systems', 'Compact nanosatellite star tracker for precision attitude determination.', '€30,000', 'Active listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (51, 'ADCS → Attitude sensors • Star', 'Star tracker', 'Sodern Auriga CP', 'https://www.cubesatshop.com/product/sodern-auriga-cp/', 'Sodern', 'Compact star tracker with indicative pricing for small-volume orders.', '€50,000 indicative', 'Published lead time: <3 months for small volumes', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (52, 'ADCS → Attitude sensors • Star', 'Star tracker', 'Sodern Auriga SA', 'https://www.cubesatshop.com/product/sodern-auriga-sa/', 'Sodern', 'Higher-end Auriga star-tracker variant.', 'From €100,000 indicative', 'Published lead time: <3 months for small volumes', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (53, 'ADCS → Attitude sensors • Sun', 'Coarse sun sensor', 'Tensor Tech CSS-10', 'https://www.cubesatshop.com/product/tensor-tech-css-10-coarse-sun-sensor/', 'Tensor Tech', 'Compact coarse sun sensor for nanosatellite attitude determination.', '$1,000', 'Active listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (54, 'ADCS → Attitude sensors • Sun', 'Digital sun sensor', 'nanoSSOC-D60', 'https://www.cubesatshop.com/product/nanossoc-d60-digital-sun-sensor/', 'SolarMEMS', 'Digital sun sensor with flight heritage and compact CubeSat form factor.', '€4,110', 'Active listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (55, 'ADCS → Attitude sensors • Sun', 'Fine sun sensor', 'CubeSpace Fine Sun Sensor', 'https://www.cubespace.co.za/products/fine-sun-sensor/', 'CubeSpace', 'Fine sun sensor for precision attitude determination.', 'Quote required', 'Published lead time: 12 weeks', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (56, 'ADCS → Attitude sensors • Sun', 'Fine sun sensor', 'NewSpace Systems Digital Fine Sun Sensor', 'https://www.cubesatshop.com/product/digital-fine-sun-sensor/', 'NewSpace Systems', 'Digital fine sun sensor sold through CubeSatShop.', '$12,000', 'Active listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (57, 'ADCS → Attitude sensors • Sun', 'Fine sun sensor', 'Tensor Tech FSS-15', 'https://www.cubesatshop.com/product/tensor-tech-fss-15-fine-sun-sensor/', 'Tensor Tech', 'Compact fine sun sensor for CubeSat ADCS.', '$1,800', 'Published lead time: 2 months', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (58, 'ADCS → Integrated ADCS', 'ADCS with magnetorquers', 'Tensor Tech ADCS-MTQ', 'https://www.cubesatshop.com/product/tensor-tech-adcs-mtq-integrated-attitude-determination-and-control-system-with-magnetorquers/', 'Tensor Tech', 'Integrated attitude determination/control system with magnetorquers for ~1U–3U missions.', '$20,000', 'Active listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (59, 'ADCS → Integrated ADCS', 'Integrated ADCS', 'CubeSpace Turnkey ADCS', 'https://www.cubespace.co.za/products/turnkey-adcs/', 'CubeSpace', 'Turnkey small-satellite ADCS combining determination, control electronics and actuators.', 'Quote required', 'Published lead time: 16 weeks', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (60, 'ADCS → Integrated ADCS', 'Integrated ADCS', 'Tensor Tech ADCS-10m', 'https://www.cubesatshop.com/product/tensor-tech-adcs-10m-integrated-attitudde-determination-and-control-system/', 'Tensor Tech', 'Integrated ADCS for small satellites using Tensor Tech actuator/sensor stack.', 'Quote required', 'Published lead time: 4–8 months', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (61, 'ADCS → Integrated ADCS', 'Integrated ADCS', 'Tensor Tech ADCS-20m', 'https://www.cubesatshop.com/product/tensor-tech-adcs-20m-integrated-attitudde-determination-and-control-system/', 'Tensor Tech', 'Higher-capacity integrated ADCS configuration.', 'Quote required', 'Published lead time: 5–10 months', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (62, 'Mechanical / Structural → Fasteners', 'Screw', 'M2.5 × 10 mm A4 Stainless Socket Cap Screw', 'https://www.accu.co.uk/metric-cap-head-screws/3964-SSCF-M2-5-10-A4', 'Accu', 'DIN 912 / ISO 4762 marine stainless fastener with certificate of conformity. Material/process still require mission review.', 'Price shown at checkout / region dependent', 'Active product; stock data updated Aug 2026', 'Engineering COTS — mission materials review required');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (63, 'Mechanical / Structural → Fasteners', 'Screw', 'M2.5 × 10 mm Grade-5 Titanium Socket Cap Screw', 'https://www.accu.co.uk/metric-cap-head-screws/652625-SSCF-M2-5-10-TI5', 'Accu', 'Grade-5 titanium DIN 912 / ISO 4762 socket cap fastener; lightweight candidate for structures.', 'Quote / regional checkout', 'Active product; stock data updated Aug 2026', 'Engineering COTS — mission materials review required');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (64, 'Mechanical / Structural → Fasteners', 'Screw', 'M2.5 × 6 mm PEEK Socket Cap Screw', 'https://www.accu.co.uk/metric-cap-head-screws/233869-SSCF-M2-5-6-PK', 'Accu', 'PEEK polymer fastener. Potentially useful where electrical isolation matters; outgassing/creep/temperature must be evaluated.', 'Quote / regional checkout', 'Active product; stock data updated Aug 2026', 'Engineering COTS — qualification required');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (65, 'Mechanical / Structural → Mechanisms • Release/Deployment', 'Ejector / deployment actuator', 'EBAD TiNi Ejector', 'https://www.cubesatshop.com/product-category/hold-down-release-mechanisms/', 'EBAD', 'TiNi deployment/ejection mechanism listed for spacecraft hold-down/release applications.', 'Quote required', 'Active CubeSatShop listing; request info', 'Flight-oriented mechanism COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (66, 'Mechanical / Structural → Mechanisms • Release/Deployment', 'Frangible actuator', 'EBAD TiNi Frangibolt', 'https://www.cubesatshop.com/product-category/hold-down-release-mechanisms/', 'EBAD', 'Shape-memory-alloy hold-down/release actuator for deployable hardware.', 'Quote required', 'Active CubeSatShop listing; request info', 'Flight-oriented mechanism COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (67, 'Mechanical / Structural → Mechanisms • Release/Deployment', 'Pin puller', 'DCUBED Micro Pin Puller (uD3PP)', 'https://www.cubesatshop.com/product/micro-pin-puller-ud3pp/', 'DCUBED', 'Small spacecraft pin-puller actuator for deployment/release functions.', 'Quote required', 'Published lead time: 10–12 weeks', 'Flight-oriented mechanism COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (68, 'Mechanical / Structural → Mechanisms • Release/Deployment', 'Pin puller', 'DCUBED Nano Pin Puller (nD3PP)', 'https://www.cubesatshop.com/product/nano-pin-puller-nd3pp/', 'DCUBED', 'Compact pin-puller for CubeSat deployable mechanisms.', 'Quote required', 'Published lead time: 6–8 weeks', 'Flight-oriented mechanism COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (69, 'Mechanical / Structural → Mechanisms • Release/Deployment', 'Release mechanism', 'DCUBED Nano SmartPack Release Nut (nD3SP)', 'https://www.cubesatshop.com/product/nano-smartpack-release-nut-nd3sp/', 'DCUBED', 'Compact hold-down/release mechanism for deployables; representative of how space systems replace ordinary hobby servos.', 'Quote required', 'Published lead time: 8–10 weeks', 'Flight-oriented mechanism COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (70, 'Mechanical / Structural → Mechanisms • Release/Deployment', 'Release nut', 'DCUBED Nano Release Nut (nD3RN)', 'https://www.cubesatshop.com/product/nano-release-nut-nd3rn/', 'DCUBED', 'Nanosatellite hold-down and release mechanism.', 'Quote required', 'Published lead time: 6–8 weeks', 'Flight-oriented mechanism COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (71, 'Mechanical / Structural → Primary structure', '12U frame', 'ISISPACE 12U CubeSat Structure', 'https://www.cubesatshop.com/product/12-unit-cubesat-structure/', 'ISISPACE', '12U CubeSat mechanical structure.', 'Quote required', 'Published availability: 8–12 weeks', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (72, 'Mechanical / Structural → Primary structure', '16U frame', 'EnduroSat 16U CubeSat Structure', 'https://www.endurosat.com/products/16u-structure/', 'EnduroSat', 'Larger 16U modular small-satellite structure.', 'See current vendor catalog', 'Active product', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (73, 'Mechanical / Structural → Primary structure', '1U frame', 'ISISPACE 1U CubeSat Structure', 'https://www.cubesatshop.com/product/1-unit-cubesat-structure/', 'ISISPACE', 'Flight-oriented 1U CubeSat mechanical structure.', '€3,450', 'Published availability: 4–6 weeks', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (74, 'Mechanical / Structural → Primary structure', '2U frame', 'ISISPACE 2U CubeSat Structure', 'https://www.cubesatshop.com/product/2-unit-cubesat-structure/', 'ISISPACE', '2U CubeSat mechanical structure.', '€4,400', 'Published availability: 4–6 weeks', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (75, 'Mechanical / Structural → Primary structure', '3U frame', 'ISISPACE 3U CubeSat Structure', 'https://www.cubesatshop.com/product/3-unit-cubesat-structure/', 'ISISPACE', 'Flight-heritage 3U CubeSat structure.', '€4,900', 'Published availability: 4–6 weeks', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (76, 'Mechanical / Structural → Primary structure', '6U frame', 'ISISPACE 6U CubeSat Structure', 'https://www.cubesatshop.com/product/6-unit-cubesat-structure/', 'ISISPACE', 'Flight-heritage 6U CubeSat structure.', '€7,950', 'Active listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (77, 'Mechanical / Structural → Primary structure', '8U frame', 'EnduroSat 8U CubeSat Structure', 'https://www.endurosat.com/products/8u-structure/', 'EnduroSat', 'Modular 8U small-satellite/CubeSat structure.', 'See current vendor catalog', 'Active product', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (78, 'Mechanical / Structural → Primary structure', '8U frame', 'ISISPACE 8U CubeSat Structure', 'https://www.cubesatshop.com/product/8-unit-cubesat-structure/', 'ISISPACE', '8U CubeSat mechanical structure.', '€9,500', 'Active listing; request info', 'Flight-oriented COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (79, 'Thermal → Active thermal control • Heater', 'Polyimide heater', 'Minco HAP6736 Satellite Heater', 'https://www.minco.com/catalog/?catalogpage=product&cid=satellite-heaters&id=HAP6736', 'Minco', 'Low-outgassing all-polyimide flexible heater intended for satellite use; NASA GSFC S-311-P-841 compliant family.', '$122', '12 reported in stock; standard lead ~7 weeks', 'Space-oriented thermal COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (80, 'Thermal → Active thermal control • Heater', 'Polyimide heater', 'Minco HAP6742 Satellite Heater', 'https://www.minco.com/catalog/?catalogpage=product&cid=satellite-heaters&id=HAP6742', 'Minco', 'Low-outgassing all-polyimide satellite heater.', '$161', '0 reported in stock; standard lead ~7 weeks', 'Space-oriented thermal COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (81, 'Thermal → Active thermal control • Heater', 'Polyimide heater', 'Minco HAP6749 Satellite Heater', 'https://sccontent.minco.com/catalog/?catalogpage=product&cid=satellite-heaters&id=HAP6749', 'Minco', 'Larger low-outgassing flexible satellite heater.', '$291', '7 reported in stock; standard lead ~7 weeks', 'Space-oriented thermal COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (82, 'Thermal → Passive thermal control • MLI', 'MLI film / blanket material', 'Dunmore Starcrest / Aerospace MLI Films', 'https://www.dunmore.com/industries/aerospace.html', 'Dunmore', 'Spacecraft-grade multilayer-insulation films, tapes and ESD materials used on NASA/ESA and commercial programs.', 'Quote required', 'Current aerospace product line; contact sales', 'Space/aerospace material');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (83, 'Thermal → Passive thermal control • MLI', 'Metallized MLI film', 'Dunmore Aerospace Metallized PET', 'https://www.dunmore.com/products/metallized-films.html', 'Dunmore', 'Aerospace-grade vacuum-metallized PET reflector film used as MLI blanket layers.', 'Quote / sample request', 'Current product; request quote/sample', 'Space/aerospace material');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (84, 'Thermal → Passive thermal control • Pad', 'Thermal gap pad', 'Bergquist GP2000S40 0.020 in', 'https://no.mouser.com/c/?q=GP2000S40-0.020-02-0816', 'Bergquist / Mouser', 'Thermal interface pad for conduction between electronics and structure.', 'NOK 973.60', '44 reported in stock', 'Engineering/aerospace COTS — qualify for vacuum');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (85, 'Thermal → Passive thermal control • Pad', 'Thermal gap pad', 'Bergquist GP3000S30 0.020 in', 'https://no.mouser.com/c/?q=GP3000S30-0.020-02-0816', 'Bergquist / Mouser', 'Thermally conductive gap pad; useful for avionics conduction paths after vacuum/materials qualification.', 'NOK 638.80', '746 reported in stock', 'Engineering/aerospace COTS — qualify for vacuum');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (86, 'Thermal → Passive thermal control • Pad', 'Thermal gap pad', 'Bergquist TGP40000SF 0.040 in', 'https://no.mouser.com/c/?q=TGP40000SF-0.040-01-0606-NA', 'Bergquist / Mouser', 'High-conductivity thermal gap pad marketed for demanding electronics/aerospace applications.', 'NOK 1,806.47', '37 reported in stock', 'Engineering/aerospace COTS — qualify for vacuum');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (87, 'Payload → Biological • Culture chamber', 'Cell culture chamber', 'ibidi 3 Well Chamber, removable', 'https://ibidi.com/89-slides', 'ibidi', 'Small multiwell chamber useful for biological payload prototyping.', '$195', 'Current store listing / order now', 'Lab COTS — substantial flight containment qualification required');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (88, 'Payload → Biological • Culture chamber', 'Microfluidic culture slide', 'ibidi µ-Slide I Luer', 'https://ibidi.com/89-slides', 'ibidi', 'Luer-connected microfluidic slide for cell culture under flow.', '$360', 'Current store listing / order now', 'Lab COTS — substantial flight containment qualification required');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (89, 'Payload → Biological • Fluid chemistry', 'Conductivity electronics', 'Atlas Scientific EZO Conductivity Circuit', 'https://atlas-scientific.com/shop/?orderby=popularity', 'Atlas Scientific', 'Embedded conductivity measurement electronics for liquid experiments.', '$67.99', 'Current store listing', 'Lab/engineering COTS — qualification required');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (90, 'Payload → Biological • Fluid chemistry', 'pH electronics', 'Atlas Scientific EZO-pH Circuit', 'https://atlas-scientific.com/embedded-solutions/ezo-ph-circuit/', 'Atlas Scientific', 'Embedded pH measurement electronics for microfluidic/biological payload prototypes.', '$45.99', 'Current store listing; add-to-cart', 'Lab/engineering COTS — qualification required');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (91, 'Payload → Biological • Gas sensing', 'CO₂ + temp + humidity sensor', 'Adafruit SCD-40 Breakout', 'https://www.adafruit.com/product/5187', 'Sensirion / Adafruit', 'CO₂, temperature and humidity sensor board useful for biological payload breadboards.', '$44.95', 'Reported in stock', 'Lab/engineering COTS — qualification required');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (92, 'Payload → Biological • Incubation', 'Incubation chamber', 'ibidi Incubation Chamber (Slide/Dish)', 'https://ibidi.com/15-instruments', 'ibidi', 'Laboratory environmental chamber for controlled microscopy/culture work; mainly useful for ground prototype and experiment validation.', '$9,560', 'Current store listing / order now', 'Ground/lab COTS — not a drop-in flight chamber');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (93, 'Payload → Biological • Pump', 'Dosing pump', 'Atlas Scientific EZO Dosing Pump', 'https://atlas-scientific.com/shop/?orderby=popularity', 'Atlas Scientific', 'Small controllable dosing pump suitable for benchtop microfluidic prototype work.', '$94.99', 'Current store listing', 'Lab/engineering COTS — qualification required');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (94, 'Payload → Biological • Pump', 'Micropump', 'Bartels mp6 Micropump', 'https://www.tccoilparts.com/productdetail/mp6-micropump', 'Bartels / distributor', 'Piezoelectric micropump for gases or liquids; common type of component for microfluidic payload development.', '~$62.37 at qty 10 (reseller listing)', 'Reseller reported stock; verify before procurement', 'Lab/engineering COTS — qualification required');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (95, 'Payload → Biological • Sequencing', 'DNA/RNA sequencer', 'MinION Mk1D', 'https://store.nanoporetech.com/eu/priceList.html', 'Oxford Nanopore Technologies', 'Palm-sized real-time nanopore sequencer; NASA-related CubeSat work has explored COTS nanopore sequencing, but integration needs substantial qualification.', '€2,940', 'Current EU store price list', 'Lab COTS — payload qualification required');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (96, 'Payload → Biological • Sequencing', 'DNA/RNA sequencer kit', 'MinION Mk1D Pack', 'https://store.nanoporetech.com/eu/priceList.html', 'Oxford Nanopore Technologies', 'MinION Mk1D pack for portable sequencing workflows.', '€4,700', 'Current EU store price list', 'Lab COTS — payload qualification required');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (97, 'Payload → Biological • Temperature', 'RTD interface', 'Atlas Scientific EZO RTD Circuit', 'https://atlas-scientific.com/shop/?orderby=popularity', 'Atlas Scientific', 'Embedded RTD temperature-measurement interface for fluid/biological experiments.', '$35.99', 'Current store listing', 'Lab/engineering COTS — qualification required');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (98, 'Payload → Biological • Valve', 'Miniature solenoid valve', 'Lee Company Dispensing Solenoid Valves', 'https://www.theleeco.com/industries/industrial-off-highway/products/solenoid-valves/dispensing-valves/', 'The Lee Company', 'Miniature precision solenoid valves for scientific/industrial fluid handling; suitable as payload development candidates.', 'Quote required', 'Current product family; contact sales', 'Engineering COTS — qualification required');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (99, 'Payload → Scientific payload • Spectrometer', 'Spectrometer', 'Argus 1000 Infrared Spectrometer', 'https://www.cubesatshop.com/product/argus-1000-infrared-spectrometer/', 'Thoth / CubeSatShop', 'Compact near-infrared spectrometer payload, <230 g, sold for CubeSat missions.', '€23,700–€55,050', 'Published availability: ~30 days', 'Flight-oriented payload COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (100, 'Propulsion → Electric propulsion', 'Thruster', 'ENPULSION IFM Nano Thruster', 'https://www.cubesatshop.com/product-category/propulsion-pressurisation/', 'ENPULSION', 'Flight-heritage electric propulsion unit for CubeSat/smallsat missions.', '€38,400', 'Active CubeSatShop listing; request info', 'Flight-oriented propulsion COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (101, 'Propulsion → Electric propulsion', 'Thruster cluster', 'ENPULSION IFM Nano Thruster Cluster', 'https://www.cubesatshop.com/product-category/propulsion-pressurisation/', 'ENPULSION', 'Clustered electric-propulsion configuration for higher thrust/power missions.', '€50,000–€210,000', 'Active CubeSatShop listing; request info', 'Flight-oriented propulsion COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (102, 'Propulsion → Micropropulsion', 'Integrated propulsion system', 'MicroSpace Nanosatellite Micropropulsion System', 'https://www.cubesatshop.com/product-category/propulsion-pressurisation/', 'MicroSpace', 'Integrated nanosatellite micropropulsion system; system-level procurement generally includes tank/feed/controller functions.', '€81,000–€129,000', 'Active CubeSatShop listing; request info', 'Flight-oriented propulsion COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (103, 'Software → Development / AIT', 'Satellite development software', 'SpaceDev', 'https://www.endurosat.com/spacedev/', 'EnduroSat', 'Software environment for bus configuration, payload integration, test, mission database and AIT workflows.', 'Quote required', 'Current offering; request demo', 'Software/service COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (104, 'Software → Mission operations', 'Mission control software', 'SpaceOps', 'https://www.endurosat.com/spaceops/', 'EnduroSat', 'Cloud mission-operations hub for telemetry, telecommand, dashboards, tasking, APIs and automation.', 'Quote / license form', 'Current SaaS offering; request demo', 'Software/service COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (105, 'Ground Segment → Development platform', 'FlatSat / development platform', 'ISISPACE CubeSat Development Platform', 'https://www.cubesatshop.com/product/isis-cubesat-development-platform/', 'ISISPACE', 'Integrated CubeSat development platform for subsystem integration and software testing.', '€79,500', 'Active listing; request info', 'Ground support COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (106, 'Ground Segment → GSE / ADCS test', 'Air bearing', 'EyasSat Single-Axis Air Bearing', 'https://www.cubesatshop.com/product-category/ground-support-equipment/', 'EyasSat', 'Single-axis air bearing for attitude-control studies and lab validation.', '$1,249', 'Active CubeSatShop listing; request info', 'Ground support COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (107, 'Ground Segment → GSE / EGSE', 'Electrical ground support equipment', 'Single Sampler EGSE', 'https://www.cubesatshop.com/product-category/ground-support-equipment/', 'Lens R&D', 'Electrical ground support equipment for spacecraft/payload testing.', '€11,887', 'Active CubeSatShop listing; request info', 'Ground support COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (108, 'Ground Segment → Ground radio', 'Ground transceiver', 'ISISPACE VHF/UHF Ground Station Transceiver', 'https://www.cubesatshop.com/product-category/ground-stations/', 'ISISPACE', 'Standalone VHF/UHF transceiver for CubeSat ground infrastructure.', '€22,500', 'Active CubeSatShop listing; request info', 'Ground COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (109, 'Ground Segment → Ground radio', 'S-band receiver', 'IQ Spacecom HISPICO S-Band Receiver', 'https://www.cubesatshop.com/product-category/ground-stations/', 'IQ Spacecom', 'S-band receiver for ground-station use.', '€7,800', 'Active CubeSatShop listing; request info', 'Ground COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (110, 'Ground Segment → Ground radio', 'Transceiver/modem', 'Teledyne QubeFlex CubeSat/SmallSat Transceiver/Modem', 'https://www.cubesatshop.com/product-category/ground-stations/', 'Teledyne', 'Ground-side transceiver/modem product for CubeSat/smallsat links.', '$8,506', 'Active CubeSatShop listing; request info', 'Ground COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (111, 'Ground Segment → Ground station', 'S-band ground station', 'ISISPACE Full Ground Station Kit for S-band', 'https://www.cubesatshop.com/product-category/ground-stations/', 'ISISPACE', 'Complete S-band ground-station kit for smallsat missions.', '€99,500', 'Active CubeSatShop listing; request info', 'Ground COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (112, 'Ground Segment → Ground station', 'VHF/UHF ground station', 'ISISPACE Full Ground Station Kit for VHF/UHF', 'https://www.cubesatshop.com/product-category/ground-stations/', 'ISISPACE', 'Complete VHF/UHF ground-station kit.', '€99,500', 'Active CubeSatShop listing; request info', 'Ground COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (113, 'Ground Segment → Ground station', 'VHF/UHF/S-band ground station', 'ISISPACE Full Ground Station Kit VHF/UHF/S-band', 'https://www.cubesatshop.com/product-category/ground-stations/', 'ISISPACE', 'Combined multi-band ground-station kit.', '€139,500', 'Active CubeSatShop listing; request info', 'Ground COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (114, 'Ground Segment → Training / test', '3U mass simulator', 'LoadPath 3U CubeSat Mass Simulator', 'https://www.cubesatshop.com/product-category/cubesat-training-simulator/', 'LoadPath', 'Mechanical mass simulator for 3U CubeSat integration/test workflows.', '$6,000', 'Active CubeSatShop listing; request info', 'Ground support COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (115, 'Other / System-level → Complete bus', '1U CubeSat platform', 'EXA KRATOS 1U CubeSat Platform', 'https://www.cubesatshop.com/product-category/cubesat-kits-buses/', 'EXA', 'Integrated 1U platform/bus sold in multiple configurations.', '€44,000–€155,000', 'Active CubeSatShop listing; request info', 'Flight-oriented spacecraft COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (116, 'Other / System-level → Complete bus', '1U–16U platforms', 'Alén Space CubeSat Platforms', 'https://www.cubesatshop.com/product/platforms/', 'Alén Space', 'Configurable 1U, 2U, 3U, 6U, 12U and 16U satellite platforms.', 'Quote required', 'Published lead time: 12 weeks', 'Flight-oriented spacecraft COTS');
INSERT INTO cubesat_cots (id, tree_location, item_type, product_name, product_url, vendor, description, published_price, availability, procurement_class) VALUES (117, 'Other / System-level → Lab satellite', 'FlatSat', 'EnduroSat DeskSat', 'https://www.endurosat.com/products/desksat/', 'EnduroSat', 'Representative flat-satellite system integrating OBC, radios, ADCS and EPS for payload/software development.', 'Current configuration price varies; prior published pre-order was $98,000', 'Current product family / inquire with vendor', 'Ground development COTS');

CREATE INDEX IF NOT EXISTS idx_cubesat_tree_location ON cubesat_cots(tree_location);
CREATE INDEX IF NOT EXISTS idx_cubesat_item_type ON cubesat_cots(item_type);
CREATE INDEX IF NOT EXISTS idx_cubesat_procurement_class ON cubesat_cots(procurement_class);
